<div id="menu">
    <div class="page-width">
        <ul class="top">
            <?php echo $this->partialLoop('index/_menuItem.phtml', $this->menu) ?>
        </ul>
        <div class="right off">
            <input type="text" onfocus="if(this.value=='search...') this.value='';" onblur="if(this.value=='') this.value='search...';" value="search..." id="mod_search_searchword" style="" alt="Search" name="q"/>
        </div>
    </div>
</div>