<div id="globalNav">
    <nav>
        <ul>
            <li class="singleColumn">
                <a title="Home" href="/">Home<span></span></a>
            </li>
            <li class=" fourColumns">
                <a title="Features" href="/features/">Features<span></span></a>
                <div class="pointer"></div>
                <div class="sub">
                    <div class="menu">
                        <ul>
                            <li class="title"><a title="JavaScript" href="/javascript/">JavaScript</a></li>
                            <li class="separator"><a href="/intl/ru/get-skype/on-your-computer/linux/">Linux</a></li>
                            <li><a href="/intl/ru/get-skype/on-your-computer/click-to-call/">Плагин Skype Click to Call</a></li>
                        </ul>
                        <ul>
                            <li class="title"><a title="JavaScript" href="/html5/">HTML5</a></li>
                        </ul>
                        <ul>
                            <li class="title"><a title="Games" href="/games/">Games</a></li>
                            <li><a title="Tanks" href="/games/tanks/">Tanks</a></li>
                        </ul>
                        <p class="otherFeatures"><a title="Главная страница раздела &quot;Загрузить Skype&quot;" href="/intl/ru/get-skype/">Главная страница раздела "Загрузить Skype"</a></p>
                    </div>
                </div>
            </li>
            <li class=" singleColumn">
                <a title="Prices" href="/">Prices<span></span></a>
                <div class="pointer"></div>
                <div class="sub">
                    <div class="menu">
                    </div>
                </div>
            </li>
        </ul>
    </nav>
</div>