<div id="globalNav">
    <nav>
        <ul>
            <li class="singleColumn">
                <a title="Home" href="/">Home<span></span></a>
            </li>
            <li class=" fourColumns">
                <a title="Features" href="/intl/ru/get-skype/">Features<span></span></a>
                <div class="pointer"></div>
                <div class="sub">
                    <div class="menu">
                        <ul>
                            <li class="title"><a title="JavaScript" href="/javascript/">JavaScript</a></li>
                            <li class="separator"><a href="/intl/ru/get-skype/on-your-computer/linux/">Linux</a></li>
                            <li><a href="/intl/ru/get-skype/on-your-computer/click-to-call/">Плагин Skype Click to Call</a></li>
                        </ul>
                        <ul>
                            <li class="title"><a title="JavaScript" href="/html5/">HTML5</a></li>
                        </ul>
                        <ul>
                            <li class="title"><a title="Games" href="/games/">Games</a></li>
                            <li><a title="Tanks" href="/games/tanks/">Tanks</a></li>
                        </ul>
                        <p class="otherFeatures"><a title="Главная страница раздела &quot;Загрузить Skype&quot;" href="/intl/ru/get-skype/">Главная страница раздела "Загрузить Skype"</a></p>
                    </div>
                </div>
            </li>
            <li class=" singleColumn">
                <a title="Цены" href="/intl/ru/prices/">Цены<span></span></a>
                <div class="pointer"></div>
                <div class="sub">
                    <div class="menu">
                    </div>
                </div>
            </li>
            <li class=" singleColumn">
                <a title="Аксессуары" href="/go/shop.accessories/">Аксессуары<span></span></a>
            </li>
            <li class=" singleColumn">
                <a title="Главная страница раздела Бизнес" href="/intl/ru/business/">Бизнес<span></span></a>
                <div class="pointer"></div>
                <div class="sub">
                    <div class="menu">
                    </div>
                </div>
            </li>
            <li class=" singleColumn">
                <a title="Главная страница раздела &quot;Поддержка&quot;" href="https://support.skype.com">Поддержка<span></span></a>
                <div class="pointer"></div>
                <div class="sub">
                    <div class="menu">
                        <ul>
                            <li class="title">Вопросы и ответы</li>
                            <li><a href="https://support.skype.com/category/CALL_QUALITY/">Проблемы со звуком</a></li>
                            <li class="separator"><a href="https://support.skype.com/category/PRIVACY__SECURITY/">Конфиденциальность и безопасность</a></li>
                            <li class="sublink"><a href="/intl/en/support/user-guides-/">Впервые у нас?</a></li>
                            <li class="sublink"><a href="http://www.skype.com/go/community">Советы экспертов</a></li>
                        </ul>
                        <p class="otherFeatures"><a title="Главная страница раздела &quot;Поддержка&quot;" href="https://support.skype.com">Главная страница раздела "Поддержка"</a></p>
                    </div>
                </div>
            </li>
        </ul>
    </nav>
</div>