<div id="globalNav">
    <nav>
        <ul>
            <li class="first fourColumns" id="HTMLID">
                <a title="Функции" href="/intl/ru/features/">Функции<span></span></a>
                <div class="pointer"></div>
                <div class="sub">
                    <div class="menu">
                        <ul>
                            <li class="title">Звонки</li>
                            <li><a href="/intl/ru/features/allfeatures/skype-to-skype-calls/">Звонки между абонентами Skype</a></li>
                            <li><a href="/intl/ru/features/allfeatures/call-phones-and-mobiles/">Стационарные и мобильные телефоны</a></li>
                            <li><a href="/intl/ru/features/allfeatures/online-number/">Онлайновый номер</a></li>
                            <li><a href="/intl/ru/features/allfeatures/conference-calls/">Телефонные конференции</a></li>
                            <li><a href="/intl/ru/features/allfeatures/skype-to-go-number/">Номер Skype To Go</a></li>
                        </ul>
                        <ul>
                            <li class="title">Видео</li>
                            <li><a href="/intl/ru/features/allfeatures/video-call/">Видеосвязь</a></li>
                            <li><a href="/intl/ru/features/allfeatures/group-video-calls/">Групповые видеозвонки</a></li>
                            <li><a href="/intl/ru/features/allfeatures/screen-sharing/">Демонстрация экрана</a></li>
                        </ul>
                        <ul>
                            <li class="title">Обмен сообщениями</li>
                            <li><a href="/intl/ru/features/allfeatures/instant-messaging/">Обмен мгновенными сообщениями (чат)</a></li>
                            <li><a href="/intl/ru/features/allfeatures/send-files/">Отправка файлов</a></li>
                            <li><a href="/intl/ru/features/allfeatures/sms/">Текстовые сообщения</a></li>
                            <li><a href="/intl/ru/features/allfeatures/facebook/">Facebook</a></li>
                        </ul>
                        <ul>
                            <li class="title">Управление</li>
                            <li><a href="/intl/ru/business/skype-manager/">Skype Manager</a></li>
                            <li><a href="/intl/ru/business/skype-connect/">Skype Connect</a></li>
                        </ul>
                        <p class="otherFeatures"><a title="Все функции " href="/intl/ru/features/">Все функции </a></p>
                    </div>
                </div>
            </li>
            <li class=" fourColumns">
                <a title="Загрузить Skype" href="/intl/ru/get-skype/">Загрузить Skype<span></span></a>
                <div class="pointer"></div>
                <div class="sub">
                    <div class="menu">
                        <ul>
                            <li class="title"><a title="Компьютер" href="/intl/ru/get-skype/on-your-computer/">Компьютер</a></li>
                            <li><a href="/intl/ru/get-skype/on-your-computer/windows/">Windows</a></li>
                            <li><a href="/intl/ru/business/download/">Windows (Business)</a></li>
                            <li><a href="/intl/ru/get-skype/on-your-computer/macosx/">Mac</a></li>
                            <li class="separator"><a href="/intl/ru/get-skype/on-your-computer/linux/">Linux</a></li>
                            <li><a href="/intl/ru/get-skype/on-your-computer/click-to-call/">Плагин Skype Click to Call</a></li>
                            <li><a href="/intl/ru/get-skype/other-downloads/">Другие приложения</a></li>
                        </ul>
                        <ul>
                            <li class="title"><a title="Мобильный" href="/intl/ru/get-skype/on-your-mobile/">Мобильный</a></li>
                            <li><a href="/intl/ru/get-skype/on-your-mobile/download/skype-for-android/">Android</a></li>
                            <li><a href="/intl/ru/get-skype/on-your-mobile/download/ipad-for-skype/">iPad</a></li>
                            <li><a href="/intl/ru/get-skype/on-your-mobile/download/iphone-for-skype/">iPhone</a></li>
                            <li><a href="/intl/ru/get-skype/on-your-mobile/download/skype-for-symbian/">Symbian</a></li>
                            <li><a href="/intl/ru/get-skype/on-your-mobile/download/skype-for-windows-phone/">Windows Phone</a></li>
                            <li><a href="/intl/ru/features/allfeatures/skype-to-go-number/">Другие телефоны</a></li>
                        </ul>
                        <ul>
                            <li class="title"><a title="Телевизор" href="/intl/ru/get-skype/on-your-tv/">Телевизор</a></li>
                            <li><a href="/intl/ru/get-skype/on-your-tv/skype-blu-ray-and-tv/">Skype для установки на телевизор</a></li>
                            <li><a href="/intl/ru/get-skype/on-your-tv/tvcam/">На ТВ с телевизионной камерой</a></li>
                            <li><a href="/intl/ru/get-skype/on-your-tv/skype-ready-tv/">Телевизоры с установленным Skype</a></li>
                        </ul>
                        <ul>
                            <li class="title"><a title="Игровые устройства" href="/intl/ru/get-skype/on-your-ps-vita/">Игровые устройства</a></li>
                            <li><a href="/intl/ru/get-skype/on-your-ps-vita/">PlayStation&reg;Vita</a></li>
                        </ul>
                        <ul>
                            <li class="title"><a title="Домашний телефон" href="/intl/ru/get-skype/home-phone/cordless-phone/">Домашний телефон</a></li>
                            <li><a href="/intl/ru/get-skype/home-phone/cordless-phone/">Беспроводные телефоны со Skype</a></li>
                        </ul>
                        <p class="otherFeatures"><a title="Главная страница раздела &quot;Загрузить Skype&quot;" href="/intl/ru/get-skype/">Главная страница раздела "Загрузить Skype"</a></p>
                    </div>
                </div>
            </li>
            <li class=" singleColumn">
                <a title="Цены" href="/intl/ru/prices/">Цены<span></span></a>
                <div class="pointer"></div>
                <div class="sub">
                    <div class="menu">
                        <ul>
                            <li><a href="/intl/ru/prices/">Бесплатные возможности</a></li>
                            <li><a href="/intl/ru/prices/payg-rates/">Оплата только сделанных звонков</a></li>
                            <li><a href="/intl/ru/prices/pay-monthly/">Подписка на месяц</a></li>
                            <li><a href="/intl/ru/prices/premium/">Skype Premium</a></li>
                            <li><a href="/intl/ru/prices/skype-credit/">Деньги на счете в Skype</a></li>
                            <li><a href="/intl/ru/prices/sms-rates/">Тарифы на SMS</a></li>
                            <li><a href="/intl/ru/prices/ways-to-pay/">Способы оплаты продуктов и услуг Skype</a></li>
                        </ul>
                        <p class="otherFeatures"><a title="Главная страница раздела &quot;Цены&quot;" href="/intl/ru/prices/">Главная страница раздела "Цены"</a></p>
                    </div>
                </div>
            </li>
            <li class=" singleColumn">
                <a title="Аксессуары" href="/go/shop.accessories/">Аксессуары<span></span></a>
            </li>
            <li class=" fourColumns">
                <a title="Главная страница раздела Бизнес" href="/intl/ru/business/">Бизнес<span></span></a>
                <div class="pointer"></div>
                <div class="sub">
                    <div class="menu">
                        <ul>
                            <li class="title">В офисе</li>
                            <li><a href="/intl/ru/business/">Обзор</a></li>
                            <li><a href="http://www.skype.com/intl/ru/business#t_home_office">Домашний офис</a></li>
                            <li><a href="http://www.skype.com/intl/ru/business#t_small_business">Малый бизнес</a></li>
                            <li><a href="http://www.skype.com/intl/ru/business#t_medium_business">Средний бизнес</a></li>
                        </ul>
                        <ul>
                            <li class="title">Продукты</li>
                            <li class="separator"><a href="/intl/ru/business/download/">Загрузка бизнес-версии</a></li>
                            <li><a href="/intl/ru/business/skype-manager/">Skype Manager</a></li>
                            <li class="sublink separator"><a href="http://www.skype.com/go/skype.manager.signin">Вход в Skype</a></li>
                            <li><a href="/intl/ru/business/skype-connect/">Skype Connect</a></li>
                        </ul>
                        <ul>
                            <li class="title">Подробности</li>
                            <li><a href="/intl/ru/business/group-video/">Групповая видеосвязь</a></li>
                            <li><a href="/intl/ru/business/case-studies/">Истории успеха</a></li>
                            <li><a href="http://blogs.skype.com/enterprise">Бизнес-блог</a></li>
                        </ul>
                        <p class="otherFeatures"><a title="Главная страница раздела Бизнес" href="/intl/ru/business/">Главная страница раздела Бизнес</a></p>
                    </div>
                </div>
            </li>
            <li class=" singleColumn">
                <a title="Главная страница раздела &quot;Поддержка&quot;" href="https://support.skype.com">Поддержка<span></span></a>
                <div class="pointer"></div>
                <div class="sub">
                    <div class="menu">
                        <ul>
                            <li class="title">Вопросы и ответы</li>
                            <li><a href="https://support.skype.com/category/CALL_QUALITY/">Проблемы со звуком</a></li>
                            <li><a href="https://support.skype.com/category/CONNECTION_ISSUES/">Проблемы с соединением</a></li>
                            <li><a href="https://support.skype.com/category/TS_ACCOUNT/">Учетная запись и личные данные</a></li>
                            <li><a href="https://support.skype.com/category/PAYMENT_PRICES/">Оплата и тарифы</a></li>
                            <li class="separator"><a href="https://support.skype.com/category/PRIVACY__SECURITY/">Конфиденциальность и безопасность</a></li>
                            <li class="sublink"><a href="/intl/en/support/user-guides-/">Впервые у нас?</a></li>
                            <li class="sublink"><a href="http://www.skype.com/go/community">Советы экспертов</a></li>
                        </ul>
                        <p class="otherFeatures"><a title="Главная страница раздела &quot;Поддержка&quot;" href="https://support.skype.com">Главная страница раздела "Поддержка"</a></p>
                    </div>
                </div>
            </li>
        </ul>
    </nav>
    <div class="searchfield">
        <form method="get" action="http://search2.skype.com/search/search.cgi" id="skypeSearchForm">
            <input type="text" maxlength="100" class="grayOut toggleTitle" title="Поиск" name="query">
            <input type="hidden" value="skype-en" name="collection"> 
        </form>		
    </div>
</div>