<div class="wrapper-outer">
    <div class="wrapper-inner">
        <section id="share" class="content-border">
            <?php
            $shareUrl = $this->baseUrl() . '/' . Zend_Controller_Front::getInstance()->getRequest()->getBaseUrl();
            $shareTitle = $this->escape($this->title);
            $shareTitle = addslashes($shareTitle);
            $showCounters = 1;
            $align = 'vertical';
            if ($showCounters == 1) {
                ?>

                <div id="fb-root"></div>
                <script>(function(d, s, id) {
                    var js, fjs = d.getElementsByTagName(s)[0];
                    if (d.getElementById(id)) return;
                    js = d.createElement(s); js.id = id;
                    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
                    fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));</script>
                <script type="text/javascript">
                (function() {
                    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                    po.src = 'https://apis.google.com/js/plusone.js';
                    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
                })();
                </script>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
            <? } ?>
            <? if ($align == 'vertical') { ?>
                <ul class="share-links" style="display: block;">
                    <li class="item twitter">
                        <a href="https://twitter.com/share" class="twitter-share-button" data-url="<?= $shareUrl; ?>"  data-lang="en" data-related="webgrrls,resource" data-count="vertical">Tweet</a>
                    </li>
                    <li class="item facebook"><div class="fb-like" data-href="<?= $shareUrl ?>" data-send="true" data-layout="box_count" data-width="58" data-show-faces="true"></div></li>
                    <li class="item google"><g:plusone size="tall" href="<?= $shareUrl ?>"></g:plusone></li>
                    <li class="item linkedin">
                        <script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
                        <script type="IN/Share" data-url="<?= $shareUrl ?>" data-counter="top"></script>
                    </li>
                </ul>
            <? } else if ($align == 'horizontal') { ?>
                <div class="share-buttons-counters">
                    <div class="item twitter">
                        <a href="https://twitter.com/share" class="twitter-share-button" data-url="<?= $shareUrl; ?>"  data-lang="en" data-related="webgrrls,resource" data-count="horizontal">Tweet</a>
                    </div>
                    <div class="item facebook">
                        <div class="fb-like" data-href="<?= $shareUrl ?>" data-send="true" data-layout="button_count" data-width="58" data-show-faces="true"></div> 
                    </div>
                    <div class="item google">
                        <g:plusone size="medium" href="<?= $shareUrl ?>"></g:plusone>
                    </div>
                    <div class="item linkedin">
                        <script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
                        <script type="IN/Share" data-url="<?= $shareUrl ?>" data-counter="right"></script>
                    </div>
                </div>
            <? }
            ?>
        </section>
    </div>
</div>