<ul id="places">
    <li data-alt="Follow us on Twitter"><a class="icon twitter" target="_blank" href="https://twitter.com/akhoroz" rel="external">Follow us on Twitter</a></li>
    <li data-alt="Contribute on github"><a class="icon github" target="_blank" href="https://github.com/andrewkhoroz/significant/" rel="external">Contribute on github</a></li>
    <li data-alt="Subscribe with RSS"><a class="icon rss"  target="blank" href="http://feeds.andrewkhoroz.com/significant" rel="external">Subscribe with RSS</a></li>
</ul>