<?php
echo $this->doctype();
?>
<html lang="en">
    <head>
        <?php echo $this->jQuery(); ?>
        <?php echo $this->headScript(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->HeadMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <meta charset="utf-8"/>
        <link rel="shortcut icon" href="<?= $this->baseUrl() . '/img/ball.ico'; ?>"/>
        <link rel="icon" type="image/gif" href="<?= $this->baseUrl() . '/img/ball.gif'; ?>"/>
    </head>
    <body>
        <div id="c-w">
            <header id="header">
                <?php echo $this->render('_header.phtml'); ?>
                <nav>
                    <?php echo $this->layout()->menu; ?>
                </nav>
            </header>
            <article id="c-main" class="page-width content-border">
                <div id="c-central" class="column left">
                    <div class="top-banner off">
                        <a href="/">
                            <img height="80" border="0" width="100%" alt="Фотогалерея" src="/img/43.jpg"/>
                        </a>
                    </div>
                    <?php echo $this->layout()->content; ?>
                    <br class="clear"/>
                </div>
                <div id="c-right" class="column right">
                    <?php echo $this->layout()->sidebar; ?>
                </div>
                <br class="clear"/>
            </article>
            <?php echo $this->render('_footer.phtml'); ?>
            <?php
            $this->addScriptPath(APPLICATION_PATH . '/views/scripts');
            echo $this->render('util/profiler.phtml');
            ?>
        </div>
        <?php echo $this->layout()->share; ?>
    </body>
</html>